---
title: "Toy Example"
output: html_notebook
---

Let us first look at the toy example. When $q=1$, $\Delta Y$ is a scalar. As our objective of the splitting is to distinguish the people/population have different treatment effect, defined with difference of differences, i.e.
\[
  \Delta Y_{T=1} - \Delta Y_{T=0}.
\],
we define the score associated with a split is
\[
  score = |S_L|Var(\Delta Y_{T=1} - \Delta Y_{T=0}|S_L) + |S_R|Var(\Delta Y_{T=1} - \Delta Y_{T=0}|S_R)
\]
To be noted, since $\Delta Y$ is a scalar, we can fix $\gamma_0, \gamma_1$, which are correspondingly scalars, at $1$ and conduct CCA, which is theoretically  equivalent to a linear regression.
```{remark}
There is the part that the formuation can have problem, since $\gamma_1-\gamma_0 = 0$, and the score will be 0 for every split. 

If we ignore the problem and proceed.
```

However, for every subject in the dataset, we can only observe either $\Delta Y_{T=1}$ and $\Delta Y_{T=0}$, but not both. It is impossible to observe $\Delta Y_{T=1} - \Delta Y_{T=0}$ for a subject directly.

### Explaination 1
Since the design of the study is a balanced randomized design, where we can assume that people in the same neighbourhood look similar, and consider matching in the local neighbourhood and use them as the unobserved treatment outcome.

### Explaination 2
Or we can think in the following way. We can force the the unobserved treatment difference of the responses to be 0. This could be interpreted as comparing the two treatments to a "baseline" difference which is 0.

For example, within a child node, before calculating the varaince, we re-order $\Delta Y$ so that
\[
\Delta Y = (\Delta Y_{T=1}, \dots, \Delta Y_{T=1}, \Delta Y_{T=0}, \dots, \Delta Y_{T=0})'
\]
And the vector that we calculate the variance is
\begin{align*}
\Delta Y_{input} &= (\Delta Y_{T=1}, \dots, \Delta Y_{T=1},-\Delta Y_{T=0}, \dots, -\Delta Y_{T=0})\\
& =  (\Delta Y_{T=1}-0, \dots, \Delta Y_{T=1}-0,0-\Delta Y_{T=0}, \dots, 0-\Delta Y_{T=0})

\end{align*}



### Explaination 3
Or we can break up
\[
Var(\Delta Y_{T=1} - \Delta Y_{T=0}) = var(\Delta Y_T=1) + var(\Delta Y_{T=0}) - 2Cov(\Delta Y_{T=1}, \Delta Y_{T=0})
\]
\[
Var(\Delta Y_{T=1} - \Delta Y_{T=0}|X^b = x) = var(\Delta Y_T=1) + var(\Delta Y_{T=0}) - 2Cov(\Delta Y_{T=1}, \Delta Y_{T=0})
\]

The difficulty of this approach is that $Cov(\Delta Y_{T=1}, \Delta Y_{T=0})$ is not 0 and hard/impossible to estimate.
