---
title: "Simulation Plan"
header-includes:
   - \usepackage{bbm}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Objective
We aim to use simulation to exame multiple dimensions of MOTTE RF and its deterministic version MOTTE TREE: Robustness against the linear assumption of treatment effect $f$ (CCA estimates the linear relationship between the two random vectors ($X$ and $\Delta X$, or $X$ and $\Delta Y$)) and the link function $g$ (Linear assumption is needed to associates $\Delta X$ and $\Delta Y$) and  respectively; correlation structure of covariates $X$s and responses $Y$; various magnitude of noise. Besides, we will put our method in a small sample size setting and big sample size setting


# Proposed Settings

* Number of Covariates: 2 settings: $p$ = 10 or 20
* Number of Responses: 2 settings: $q$ = 3 or 6
* Sample Size for Training Data: $N_{train}$ = 400 or 800
* Sample Size for Testing Data: $N_{test}$ = 1000
* Number of Iteration: 1000
* Covariance Matrix for Covariates: $\Sigma = \mathbb{I}$ or $AR(0.8)$
* Simulation
  \begin{align*}
  X^b & \sim MVN(0, \Sigma)\\
  X^e & \sim MVN(X^b + I(T=1)f_{T=1}(X^b) - I(T=-1)f_{T=-1}(X^b), c_x\mathbb{I})\\
  Y & \sim MVN(g(X), c_y\mathbb{I})
  \end{align*}
* Variation/error:
  + $\Sigma$ for pre-treatment covariates $X^b$: Doesn't matter, but prefer to be large to have wider range of sample 
  + $c_x$ for Post-treatment covariates $X^e$ error term: need to calculate the signal-noise ratio, which is based on treatment effect function
  + $c_y$ Linking error, i.e. $x \rightarrow y$: another signfal-noise ratio. And should consider the noise from treatment effect propogate
* Treatment function: 
\[
  \mathbb{E}(X^e) = X^b + I(T=1)fX^b) - I(T=-1)f(X^b),
\]
where $f(\cdot)  = f_{T=1}(\cdot) = - f_{T=-1}(\cdot)$. This is the most simple case where the treatment function of each arm lies in the same plane. Otherwise, we need to set up treatment function in different dimensions. $f(\cdot)$ function can be one of the following options
  + Linear: $f(X) = X\beta$
  + Polynomial: $f(x) = (X\circ X) \times \beta$ where $A \circ B$ is the hadamard product
  +  Depending on the choice of $\beta_{p \times p}$, we can control if we want to introduce correlation into $X^e$$
    - Do not impose more correlation for $X^e$
      \[
        \beta = \mathbb{I}_{p \times p}
      \]
      or
      \[
        \beta = \begin{pmatrix} \mathbb{I}_{5\times 5} & \mathbf{0}_{5\times (p-5)}\\
        \mathbf{0}_{(p-5) \times 5} & \mathbf{0}_{(p-5) \times (p-5)}
        \end{pmatrix}
      \]
    - Impose more correlation for $X^e$
      \[
        \beta = 
          \begin{pmatrix} 
            \mathbf{1}_{3\times 1} & \mathbf{0}_{3\times 1} & \mathbf{0}_{3\times 1} &\mathbf{0}_{3 \times (p-3)}\\
            \mathbf{0}_{3 \times 1} & \mathbf{1}_{3 \times 1} & \mathbf{0}_{3\times 1} & \mathbf{0}_{3 \times (p-3)}\\
            \mathbf{0}_{3 \times 1} & \mathbf{0}_{3 \times 1} &\mathbf{1}_{3 \times 1} &\mathbf{0}_{3 \times (p-3)}\\
            \mathbf{0}_{(p-9) \times 1} & \mathbf{0}_{(p-9) \times 1} & \mathbf{0}_{(p-9) \times 1} & \mathbf{0}_{(p-9) \times (p-3)}
          \end{pmatrix}
      \]
    
* Link function:
  + Linear: \[\mathbb{E}(Y) = g(X) =  X \times Z\]
  + Non-Linear: \[\mathbb{E}(Y) = g(X) = (X \circ X) \times Z\]
  + $Z_{p*q}$
  \[
      Z = 
      \begin{pmatrix}
        \mathbf{1}_{3\times 1} & \mathbf{0} & \mathbf{0}\\
        \mathbf{0} & \mathbf{1}_{3\times 1} &  \mathbf{0}\\
        \mathbf{0}  &  \mathbf{0} & \mathbf{1}_{3\times 1}\\
        \mathbf{0} & \mathbf{0} & \mathbf{0}
      \end{pmatrix}
  \]
    
* Metrics Evaluated
  + Treatment Effect (\& its variance): 
  \[ \mathbb{E}(Y^e|T=1) - \mathbb{E}(Y^e|T=-1)\]
  + Treatment Recommendation: The reason that I would like to see something about it is because, at the end, we would like to apply this in a real life scenario where the recommendation are given.
  \[\mathbb{I}\left[w\mathbb{E}(Y^e|T=1) - w\mathbb{E}(Y^e|T=-1)\right]\]
